include: package:flutter_lints/flutter.yaml

linter:
  rules:

# 警告が出るため、以下のanalyzerを追加
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
